//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSubscription
    {
        public int Id { get; set; }
        public string SubEmail { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
