//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransection
    {
        public int ID { get; set; }
        public int FK_Customer { get; set; }
        public int FK_OrderMAster { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public string StripePaymentID { get; set; }
        public string PaypalPaymentID { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual OrderMaster OrderMaster { get; set; }
    }
}
