//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2C_Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDeliveryPartner
    {
        public int Id { get; set; }
        public string PartnerName { get; set; }
        public string TripId { get; set; }
        public string EventTime { get; set; }
        public string EventStatus { get; set; }
        public string TripTime { get; set; }
        public string PartnerMobile { get; set; }
        public string PlateNo { get; set; }
        public Nullable<double> PartnerLat { get; set; }
        public Nullable<double> PartnerLng { get; set; }
        public string TrackingLink { get; set; }
        public Nullable<double> InvoiceTotal { get; set; }
        public string DeliveryMessage { get; set; }
        public string DeliveryStatus { get; set; }
        public int FK_RiderId { get; set; }
        public int FK_OrderId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBY { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBY { get; set; }
        public string BookingId { get; set; }
        public bool IsActive { get; set; }
        public string EventName { get; set; }
    }
}
